version: "3.6"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  postgres-storage:
    driver: local

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage
    environment:
      POSTGRES_USER: schedule
      POSTGRES_PASSWORD: 0000
