version: "3.6"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  postgres-storage:
    driver: local
  rabbitmq-storage:
    driver: local

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: tech

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq-storage
